- hosts: localhost
  become: yes
  
  tasks:

  - name: Update apt caches
    apt:
      update_cache: yes

  - name: Install dependencies
    apt: 
      name:
        - build-essential
        - python3-pip
        - python3-dev

  - name: Install Ansible dependencies
    pip:
      name:
        - ansible
        - pymongo  

  - name: Install Node.js
    apt:
      name: nodejs

  - name: Install pnpm
    npm:
      name: pnpm
      global: yes

  - name: Install yarn
    npm:
      name: yarn
      global: yes

  - name: Install MongoDB
    apt:
      name: mongodb-org

  - name: Install MySQL
    apt:
      name: mysql-server

  - name: Install Nginx
    apt:
      name: nginx

  - name: Install PM2
    npm:
      name: pm2
      global: yes

  - name: Start MongoDB
    service:
      name: mongod
      state: started

  - name: Start MySQL
    service:  
      name: mysql
      state: started

  - name: Start Nginx
    service:
      name: nginx
      state: started







      