---
- hosts: '{{ selected_server }}'
  remote_user: '{{ target_user }}'
  vars:
    ansible_ssh_pass: '{{ ssh_password if ssh_password is defined else omit }}'
    ansible_ssh_private_key_file: '{{ ansible_ssh_private_key_file if ansible_ssh_private_key_file is defined else omit }}'
    ansible_become_pass: '{{ ansible_become_pass }}'
    ansible_become_method: sudo

  vars_prompt:
    - name: 'new_user'
      prompt: 'Enter the username for the new user'
      private: no
    - name: 'new_user_password'
      prompt: 'Enter the password for the new user'
      private: yes

  tasks:
    - name: Install acl
      apt:
        name: acl
        state: present
      become: yes

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      notify: restart nginx

    - name: Add a new user
      user:
        name: '{{ new_user }}'
        password: "{{ new_user_password | password_hash('sha512') }}"
        groups: sudo
      become: yes

    - name: Fetch latest NVM version
      shell: 'curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .tag_name'
      register: latest_nvm_version
      become: yes

    - name: Install latest NVM version
      shell: |
        export NVM_VERSION="{{ latest_nvm_version.stdout }}"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
      become: yes

    - name: Install essential packages
      apt:
        name:
          - gcc
          - g++
          - make
          - nginx
          - mysql-server
      become: yes
      ignore_errors: true

    - name: Start essential services
      systemd:
        name: '{{ item }}'
        state: started
      loop:
        - nginx
        - mysql
      become: yes

    - name: Install Node.js global packages
      npm:
        name: '{{ item }}'
        global: yes
      loop:
        - pm2
        - pnpm
      become: yes

    - name: Install Yarn package manager
      shell: |
        curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt-get update && sudo apt-get install yarn
      become: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
      become: yes
