- hosts: localhost
  become: yes

  tasks:

  - name: Update apt cache
    apt: 
      update_cache: yes

  - name: Install build tools
    apt:
      name:
        - build-essential
        - python3-pip

  - name: Install Ansible dependencies
    pip:
      name:
        - ansible
        - pymongo

  - name: Install NVM
    shell: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  

  - name: Install Node.js
    shell: nvm install node

  - name: Install Yarn
    npm:
      name: yarn
      global: yes

  - name: Install PNPM
    shell: |
      npm install -g pnpm

  - name: Install MongoDB
    apt:
      name: mongodb-org

  - name: Install MySQL
    apt:
      name: mysql-server

  - name: Install Nginx
    apt: 
      name: nginx

  - name: Install PM2
    npm:
      name: pm2
      global: yes

  - name: Start MongoDB
    service:
      name: mongod
      state: started
  
  - name: Start MySQL
    service:
      name: mysql
      state: started

  - name: Start Nginx
    service:
      name: nginx
      state: started