name: Build and Deploy FRONTEND

env:
  PROJECT_NAME: avrean_dashboard

on:
  push:
    branches:
      - '*'
    paths:
      - 'frontend/**/*'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm for frontend
        run: npm install -g pnpm
      - name: Install frontend dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run frontend lint and build
        run: |
          pnpm run lint
          pnpm run build

  deploy-frontend:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && success()
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set environment
        run: echo "DEPLOY_ENV=$(if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then echo 'dev'; else echo 'prod'; fi)" >> $GITHUB_ENV
      - name: SSH and Prepare Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets["DEV_SERVER_HETZNER_IP"] }}
          username: ${{ secrets["DEV_SERVER_HETZNER_USER"] }}
          password: ${{ secrets["DEV_SERVER_HETZNER_DEV_PASSWORD"] }}
          script: |
            mkdir -p /home/${{ secrets["DEV_SERVER_HETZNER_USER"] }}/sites/${{ env.PROJECT_NAME }}/${{ env.DEPLOY_ENV }}/frontend
            rm -r /home/${{ secrets["DEV_SERVER_HETZNER_USER"] }}/sites/${{ env.PROJECT_NAME }}/${{ env.DEPLOY_ENV }}/frontend
            mkdir -p /home/${{ secrets["DEV_SERVER_HETZNER_USER"] }}/sites/${{ env.PROJECT_NAME }}/${{ env.DEPLOY_ENV }}/frontend
      - name: SCP frontend to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets["DEV_SERVER_HETZNER_IP"] }}
          username: ${{ secrets["DEV_SERVER_HETZNER_USER"] }}
          password: ${{ secrets["DEV_SERVER_HETZNER_DEV_PASSWORD"] }}
          source: 'frontend/dist' # Usually, you'll want to copy only the 'dist' folder, adjust as needed
          target: /home/${{ secrets["DEV_SERVER_HETZNER_USER"] }}/sites/${{ env.PROJECT_NAME }}/${{ env.DEPLOY_ENV }}/frontend
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets["DEV_SERVER_HETZNER_IP"] }}
          username: ${{ secrets["DEV_SERVER_HETZNER_USER"] }}
          password: ${{ secrets["DEV_SERVER_HETZNER_DEV_PASSWORD"] }}
          script: /home/dev/scripts/start_${{ env.PROJECT_NAME }}_${{ env.DEPLOY_ENV }}_f.sh
